title: "Portafolio – Edison H."
description: "Desarrollo de Aplicaciones Web – UNCP"
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM

url: "https://edison1000msnmsn.github.io"
baseurl: "/PORTAFOLIO"
